name: Noticeboard
main: se.peacehult.oskyedz.noticeboard.NoticeBoard
version: '0.1'
author: OskyEdz
api-version: '1.15'
website: https://peacehult.se
commands:
  noticeboard:
    description: Open a Notice Board
    usage: Use §c/noticeboard
  noticeboard new:
    description: Add a new notice
    usage: Use §c/noticeboard new <Title> <lore>
